### ISSUE TITLE
Rework everything to work properly and store data in reliable formats

### ISSUE THREAD

**Issue by LiaAiluri** [pamaxie/Pamaxie.Database_API#1]
Currently data storage doesn't make a lot of sense. We need to completely rewrite how our native driver works and make it work better with Docker.

**Comment by Leejja** [comment]
I'm Currently documenting all API endpoints to make sure we have a well thought through design before continuing work on this.

**Comment by Leejja** [comment]
Documentation has been finished after roughly 2 days of work (8 hours + 4 hours)

**Comment by Leejja** [comment]
Starting implementation of API endpoints now

**Comment by Leejja** [comment]
I saw there was some inconsistencies between the User and Business data while writing the conversion for NoSQL storage. Addressed this and continuing work on starting the implementation of the API endpoints.

**Comment by Leejja** [comment]
Finished Implementation on API Endpoints - 1c3c1dac832de0b876f21c02542a56839f1d14ff
Starting validation, making sure input cannot be tinkered with for malicious use.

**Comment by Leejja** [comment]
Finished the database rework from a functional basis. Attempting initial rollout as docker containers now. Might report back with issues regarding to docker configuration.

**Comment by LiaAiluri** [comment]
This is probably not feasable without rewriting the entire API. This will be closed for now and we will do a rewrite to GraphQL #19. This is because there is too many issues with our current storage / query format and it makes our API needlessly complex.
